<?php

namespace Modules\WebsiteBase\database\factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Modules\WebsiteBase\app\Models\Address;

class AddressFactory extends Factory
{
    protected $model = Address::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {
        return [
            'is_public'        => fake()->boolean(),
            'title'            => fake()->title(),
            'firstname'        => fake()->firstName(),
            'lastname'         => fake()->lastName(),
            'street'           => fake()->streetAddress(),
            'city'             => fake()->city(),
            'region'           => implode(' ', fake()->words(rand(1, 4))),
            'country_iso'      => fake()->countryCode(),
            'email'            => fake()->email(),
            'phone'            => fake()->phoneNumber(),
//                        'auto_region_id'            => ...,
            'user_description' => 'generated by factory',
        ];
    }
}
